print("Good Morning..")
print('Welcome') 
print("Programming", "Essentials", "in", sep="***", end="...")
print("Python")

print("      *       " *2)
print("     * *      " *2)
print("    *   *     " *2)
print("   *     *    " *2)
print("  *       *   " *2)
print(" ***     ***  " *2)
print("   *     *    " *2)
print("   *     *    " *2)
print("   *******    " *2)